const nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
    service: 'gmail',
    // vvv optional settings, email will be sent with or without these options vvv
    host: "smtp.gmail.com",
    port: 465,  
    // ^^^ optional settings, email will be sent with or without these options ^^^
    auth: {
        user: 'ppapmaster00@gmail.com',
        pass: 'xfmo ievx zcsx htub' //this is an app password generated by google and not the actual password (will be deleted later)
    }
});

var message = {
    from: 'ppapmaster00@gmail.com',
    to: 'oussailsam321@gmail.com',
    subject: 'Sending Email using Node.js',
    text: 'test mail sending from node'
};

transporter.sendMail(message, (err,info) => {
    if(err) throw err;
    
    console.log(`Email sent: ${info.response}`);
});

// app password: xfmo ievx zcsx htub